apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
      - name: lab
        image: oscarfonts/h2
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: lab
spec:
  selector:
    app: lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

